### ISSUE TITLE
Improve fulltext indexing for large files

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#116]
See https://cern-rcs-sis.zulipchat.com/#narrow/stream/310485-inspire/topic/PDF.20reduction/near/293130006. This is related to #111.

**Comment by MJedr** [comment]
The problem here is that we don't download files from URL to file (we use s3 stream currently). What we can do is have s3 buckets with files processed with `ghostscript` (we can do it on the `add_file` task if the new file is added or the file is modified) and, then, download the data from the new buckets.
