### ISSUE TITLE
"Date of paper" facet doesn't work

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#131]
When you go to Literature then go to Authors and come back to Literature, date facet doesn't work

https://user-images.githubusercontent.com/4287772/188116671-d25295df-9419-48e4-83f5-3bb521fda93e.mov

**Comment by MJedr** [comment]
The problem is with all the facets and aggregrations - when we go to another collection we [reset query](https://github.com/inspirehep/inspirehep/blob/1dcfbe164f0595b732473b05d4d0fd738554d19e/ui/src/middlewares/syncLocationWithSearch.js#L78) (so it is reverted to the base query) and when we go back to search page in literature, the query is the same (base query) so we don't notice [here](https://github.com/inspirehep/inspirehep/blob/1dcfbe164f0595b732473b05d4d0fd738554d19e/ui/src/search/queryChange.js#L11-L12) any change and we don't fetch aggregations. As a result we stay with old aggregations. So for example when last search was `a moskovic` and we go to authors and back to literature we have saved aggregations for `a moskovic` which is totally wrong. We need to have another mechanism to detect query change, I would suggest to do it based on location.

**Comment by karolina-siemieniuk-morawska** [comment]
**TECH NOTES:** 

1. We need to trigger [fetchSearchAggregations](https://github.com/inspirehep/inspirehep/blob/42f68b651d0c8e16593471d6d1d4b9c221244b75/ui/src/actions/search.js#L92) also on location change. A way to do this is to move execution of ```fetchSearchAggregations``` from [here](https://github.com/inspirehep/inspirehep/blob/1dcfbe164f0595b732473b05d4d0fd738554d19e/ui/src/search/queryChange.js#L14) to line 20.
