### ISSUE TITLE
Improve `citedby` query parsing

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#137]
There are two issues with the current `citedby:recid:` approach:
* it works only with a literal string of the form `citedby:recid:{recid}`, instead of using a proper parser. So things like `citedby recid 42` or `citedby:recid:      42` don't work. It would be better to let the query parser do the actual parsing if possible and transform the generated query to substitute uuids for record IDs.
* there is a bug when `citedby` searches are performed as in https://github.com/inspirehep/inspirehep/blob/18ea83a67633fe7b8c955f3dd0d595f1d63f5df5/backend/tests/integration/search/test_factories_query.py#L59 and a record ID appears as a substring of a previously substitued uuid. This would probably be rare in production but causes flaky tests.

**Comment by MJedr** [comment]
**TECH NOTES**
1. Remove [this](https://github.com/inspirehep/inspirehep/blob/18ea83a67633fe7b8c955f3dd0d595f1d63f5df5/backend/inspirehep/search/factories/query.py#L17-L29)
2. In query parser we will create a query with a synthetic key which will be replaced later. So [here](https://github.com/inspirehep/inspire-query-parser/blob/352a92961acd6336c6efbdf458dde9ce60aea9fa/inspire_query_parser/visitors/elastic_search_visitor.py#L594) put `temp_recid_for_uuid` instead of `id`.
3. In [LiteratureSearch](), if `citedby` was a part of the query string get the value of the key `temp_recid_for_uuid` (or all the values in the query, might be more than one), fetch the uuids for the recids and then replace all the key-value pairs `temp_recid_for_uuid`: `recid` with `id`: `uuid`. It can be done with [this](https://pypi.org/project/nested-lookup/)
