### ISSUE TITLE
don't hide closed jobs for users

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#146]
From https://rt.inspirehep.net/Ticket/Display.html?id=1281238:

currently we're hiding closed jobs to users. This is done because it was done similarly on legacy, but there is no good reason to do that, and it prevents users from using the jobs database to collect statistics about the field.

What should be changed:
* Allow users to see both `open` and `closed` `status` jobs (**not `pending`**).
* Display a dropdown like for curators for `status` (defaulting to `open`).
* Add a default facet `status=open` to the search query for users.

**Comment by MJedr** [comment]
**TECH NOTES**
* change the query [here](https://github.com/inspirehep/inspirehep/blob/a6202ce99f5bad49ca3592f6ee609f4eb3fc5424/backend/inspirehep/search/api.py#L390) and [here](https://github.com/inspirehep/inspirehep/blob/a6202ce99f5bad49ca3592f6ee609f4eb3fc5424/backend/inspirehep/search/api.py#L396) to `terms` and add `status=['open', 'closed']`
* for the facet add a new aggregation which will be similar to [this one](https://github.com/inspirehep/inspirehep/blob/a6202ce99f5bad49ca3592f6ee609f4eb3fc5424/backend/inspirehep/search/aggregations.py#L150) but will exclude option `pending` (for excluding fields from aggregation check [this](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_filtering_values_4)). Refactor facets so that the new aggregation ends up in `records_jobs` but not in `records_jobs_cataloger`.
