### ISSUE TITLE
claiming from literature search page only works for first few authors

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#182]
It looks like claiming from the Literature search page only takes into account authors that are part of the search result payload to populate the drawer, so further authors can't claim (at least if it would lead to a drawer appearing). For example, https://inspirehep.net/literature?sort=mostrecent&size=25&page=1&q=recid%3A1963152 leads to a drawer for `Subir Sarkar` (two `Sarkar, S.` on the paper), but he doesn't appear in the drawer.

**Comment by karolina-siemieniuk-morawska** [comment]
**TECH NOTES:**
- in [literature.ts](https://github.com/inspirehep/inspirehep/blob/d430472db2731239832c23a89b683ff888e36680/ui/src/actions/literature.ts) add fetchAllLiteratureAuthors function that will fetch authors from /api/literature/123?field=authors
- in [<LiteratureSearchContainer />](https://github.com/inspirehep/inspirehep/blob/2ea2747dfd1c2c18913be17a746f88926245a9f3/ui/src/literature/containers/LiteratureSearchContainer.jsx) pass all authors to `<LiteratureItem />` as prop
- in `<LiteratureItem />` delete authors field taken from metadata and use the one from props, so that `AssignLiteratureItemDrawer` receives all authors
