### ISSUE TITLE
upgrade to python 3.11

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#188]
Currently, in our project, we use Python 3.8, however, Python 3.11 is available which is significantly faster than its predecessors. We need to upgrade it. 

**Unfortunately, it is not possible to install lxml on macos due to missing wheels for Python > 3.9.** There is an [issue, opened recently,](https://bugs.launchpad.net/lxml/+bug/1998212) to add them, we should keep track of it.

**Comment by michamos** [comment]
another issue is the change in `collections`: abstract base classes need to be imported from `collections.abc` instead of `collections`. This will require updating several dependencies (see for example https://inspirehep.zulipchat.com/#narrow/stream/122199-ops/topic/DESY.20harvest/near/329399196).

**Comment by MJedr** [comment]
Not sure if it will be possible because:
* there's a known bug in pytest for python >= 3.10, we need to upgrade it to version 6.2.5
* then, we get the error from elasticsearch library, because the elasticsearch we currently use support python <3.9
* elasticsearch is locked by invenio search in version <8.0.0, and python >3.9 is supported from the version 8.0.0

**Comment by PascalEgn** [comment]
Needs removal of hepcrawl dependency first, see https://github.com/cern-sis/issues-inspire/issues/494 for more info
