### ISSUE TITLE
Link workflow ids in error message on holdingpen

### ISSUE THREAD

**Issue by MJedr** [cern-sis/issues-inspire#20]
Link wf id to the workflow page (so `4074622` in this error message should link to https://inspirehep.net/holdingpen/4074622)
`WorkflowsError: Cannot continue processing workflow 4081377.Found not-completed workflows in holdingpen : [4074622]`

**Comment by drjova** [comment]
TECH NOTES:
* Add links here instead of just ids https://github.com/inspirehep/inspire-next/blob/f6a1c5812c48dfbfa9ddbd79886085e50622116f/inspirehep/modules/workflows/tasks/matching.py#L315-L321
* Add a plugin for this part of the template to make links clickable https://github.com/inspirehep/inspirehep-search-js/blob/421f4936dc57f69d9dcf42942e3f2ec1f74188b0/src/inspirehep-holdingpen-js/templates/inspirehep-holdingpen-js/details/details_errors.html
