### ISSUE TITLE
SNOW integration on next

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#266]
Checklist for refinement
- [ ] Make sure to use the inspirehep API
- [ ] FEATURE FLAG to enable the new SNOW API 
- [ ] FEATURE FLAG to enable the queues replacement

**Comment by MJedr** [comment]
1. We need an API on hep supporting following operations:
- create ticket (`snow's create_inspire_ticket`/`create_inspire_ticket_with_template`)
- reply ticket (snow's `edit_ticket`)
- resolve ticket (change status `resolve_ticket`).

Since on next we have only user_id it would be necessary to translate `user_id` into `user_email`.

Add an API to /tickets/views.

2. On next:
 - replace current API with api calls in https://github.com/inspirehep/inspire-next/blob/5a0a5533b883ceebc6cddd48ede4c7e320d76a2a/inspirehep/modules/workflows/tasks/submission.py#L54
 - Adjust all the calls on next to use proper methods and arguments
 - remove some rt leftovers from editor/views https://github.com/inspirehep/inspire-next/blob/5a0a5533b883ceebc6cddd48ede4c7e320d76a2a/inspirehep/modules/editor/api.py#L120-L173
 - Also, everything should be behind a feature flag so that we supoort rt in parallel
