### ISSUE TITLE
Replace `retry_until_pass` with tenacity

### ISSUE THREAD

**Issue by MJedr** [cern-sis/issues-inspire#278]
Since we tested Tenacity's retry for assertions in async tests we need to replace all the `retry_until_pass` calls with `retry` from tenacity.

**Comment by MJedr** [comment]
**TECH NOTES**
Replace `retry_until_pass` by adding a decorator `@retry(stop=stop_after_delay(10))` above the assertion functions in tests/integration-async.

**Comment by drjova** [comment]
@PascalEgn thank you! We can remove the `retry_until_pass` all together, if we don't use it anywhere else.

**Comment by PascalEgn** [comment]
> @PascalEgn thank you! We can remove the `retry_until_pass` all together, if we don't use it anywhere else.

I will, also one test fails during the GitHub action (but worked locally). I guess this is because I mostly went with `stop=stop_after_delay(10)`, but in `retry_until_pass` we had a default timeout of 30 secs and a default wait between tries of 0.3 secs. Should I just apply these settings to the new retry decorator e.g. `@retry(stop=stop_after_delay(30), wait=wait_fixed(0.3))`?

**Comment by drjova** [comment]
Yes, please update it.
