### ISSUE TITLE
desy harvest: delete files only when the record is on hep

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#297]
When we harvest desy, we move the `jsonl` file immediately to the processing bucket, and if we restart the workflow, we can no longer process it. We should also add the file in the `acquition_source`

An error example:

```python
  File "/usr/lib/python2.7/site-packages/hepcrawl/spiders/desy_spider.py", line 254, in _parsed_items_from_json
    document['url'] = self._get_full_uri(document['url'])
  File "/usr/lib/python2.7/site-packages/hepcrawl/spiders/desy_spider.py", line 171, in _get_full_uri
    self.move_file_to_processed(file_name)
  File "/usr/lib/python2.7/site-packages/hepcrawl/spiders/desy_spider.py", line 232, in move_file_to_processed
    processed_bucket.copy(source, file_name)
  File "/usr/lib/python2.7/site-packages/boto3/s3/inject.py", line 431, in bucket_copy
    Callback=Callback, SourceClient=SourceClient, Config=Config)
  File "/usr/lib/python2.7/site-packages/boto3/s3/inject.py", line 379, in copy
    return future.result()
  File "/usr/lib/python2.7/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/usr/lib/python2.7/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
```

**Comment by MJedr** [comment]
This is an error that comes from the crawler, not from the workflow. In that case we should restart harvest rather than the workflow. Also, since there are many records in one jsonl and workflows are independent tasks it will be very hard to know if all the workflows are created out of one jsonl file.

**Comment by michamos** [comment]
Isn't this error caused by simultaneous overlapping runs of the DESY harvest? if it's too slow and doesn't finish before the next one starts, then the second one will start processing jsonl and attached documents in `incoming`. This causes issues because the jsonl and all referred documents are not moved to the `processed` bucket atomically, so they might encounter a situation where the files have already been moved to `processed` but the jsonl not yet by the other concurrent harvest.

**Comment by MJedr** [comment]
Seems reasonable, but I am not sure if the harvest itself is not that slow. IMO, what we can do now to improve the situation is to add the name of the jsonl file to the workflow so that it will be much easier to rerun the harvest. Implementing other logic will be much more difficult and we would like to avoid changes next. Also, we asked not to put that many json files in jsonl so that should improve the situation.
