### ISSUE TITLE
on self curation check if possible to compare the raw affiliation to verify the reference index

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#340]
This should be split into two tasks, backend and ui.

**Comment by MJedr** [comment]
We don't pass `raw_refs` to the frontend. So either we make sure in the frontend that we don't mess up the indices in the paginated list or we need to add raw_refs to the serializer and return it back to the backend on reference edit.

**Comment by michamos** [comment]
@MJedr can we maybe discuss what this is about? I'm not sure I understand, but from my limited understand it looks like you're making assumptions on `raw_refs` here that are not necessarily true.

**Comment by michamos** [comment]
After discussion, turns out we have some logic to bring up the correct `raw_ref` (accounting for pagination) but we don't trust it 100%. @karolina-siemieniuk-morawska tested it on a few cases, and I'll test it again. As this is only shown to curators, it's good enough to ask them to be careful and report any issues with raw refs that don't match.
