### ISSUE TITLE
only flag primary categories as core

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#39]
From https://inspirehep.zulipchat.com/#narrow/stream/195298-experts/topic/Auto-CORE.20only.20for.20prim-cat/near/282082678

Currently, we auto-ingest and tag as core all papers in some arXiv categories. We want to change that in order to:
* tag as core only papers whose **primary category** (first element of `arxiv_eprints.categories`) is one of the core categories
* still auto-ingest those categories.

This requires changing https://github.com/inspirehep/inspire-next/blob/a442fd80476e48fe37eb9a2c6e0854c487eb2caf/inspirehep/modules/workflows/tasks/matching.py#L226 to only look at the primary category.

**Comment by MJedr** [comment]
**TECH NOTES**
* add a new function `_is_first_category_core` which will be used [here](https://github.com/inspirehep/inspire-next/blob/a442fd80476e48fe37eb9a2c6e0854c487eb2caf/inspirehep/modules/workflows/tasks/matching.py#L226-L227). 
* since [`is_core`](https://github.com/inspirehep/inspire-next/blob/a442fd80476e48fe37eb9a2c6e0854c487eb2caf/inspirehep/modules/workflows/tasks/matching.py#L213-L219) is used only for checking if secondary category is core, rename it to `is_second_category_core` and remove optional argument `only_secondary_categories` - it should be true by default
