### ISSUE TITLE
Update Resolution options for authors

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#522]
We have to add `accept_curate` in the resolution options and it should run the `author_create_approved_dag` dag as well.

# TECH NOTES

* It should work with https://github.com/inspirehep/backoffice/blob/main/backoffice/backoffice/workflows/api/views.py#L159

**Comment by karolina-siemieniuk-morawska** [comment]
**TECH NOTES (for UI):**

1. In [AuthorDetailPageContainer.tsx ](https://github.com/inspirehep/inspirehep/blob/3ec50ba958129b7a69116baac3c688415ea6e88c/ui/src/holdingpen-new/containers/DetailPageContainer/AuthorDetailPageContainer.tsx#L346-L353)use correct endpoint and payload.

**Comment by DonHaul** [comment]
Weird side effect of using the choices meant for something else is that instead of `accept` and `accept_curate` we get the dag that should be executed in django. Althouh in posgres we see the correct action


![Image](https://github.com/user-attachments/assets/3465aa62-406d-4906-9446-dcc869aa73cd)


![Image](https://github.com/user-attachments/assets/573d1ade-4aa2-49b4-801e-5e965c33462c)
