### ISSUE TITLE
How to integrate ui to the backoffice repo

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#551]
Currently, developing our project is somewhat cumbersome due to the separation of the UI, which resides in the inspirehep repository, from the rest of the codebase in the backoffice repository. This setup complicates the development workflow and increases the maintenance overhead.

Proposed Solutions:
- Integrate the UI as a Git submodule within the backoffice repository.
- Move the backoffice code into the inspirehep repository to consolidate the codebases.
- Release the UI as a standalone package (though this is not the ideal solution due to potential complexity in version management and dependency handling).
- Explore other potential methods for better integration.

Outcome:
The goal of this issue is to define a clear and efficient way to integrate the UI with the backoffice to improve the development experience and reduce overhead. We should discuss the above options and any other suggestions to arrive at the best solution.

**Comment by DonHaul** [comment]
I would go for one of the 3
1. Have all on the same repo - best for local development and testing - have some options in make  file to run all or only run some of the services depending on what are we developing.
   - Best option if we wish to perform e2e tests
2. Have 2 repos - one inspirehep, the other backoffice which would contain also contain the new holding pen ui -
   -  since inspirehep is stable it would be okay to keep it separate.
   - when we need to do changes to it it does not have dependencies on backoffice so it can be spun up alone
   - for backoffice we would have to use the qa inspire hep.
3.  Have 3 repos
    - same as previous one but besides having these 2 repos, we would have a global inspire repo that would import these aforementioned 2 repos as submodules - same benefits as option above, with the added benefit that we can also run it all locally and make sure all works well. - the global repo would probably rarely be used as it would just for the case we want to have everything running locally.

All of these would require a require a review of the docker compose to make sure there are no `ports` clashing and alike when we are running all these services at the same time in our machine.

I favour option 1 and 3

**Comment by drjova** [comment]
The best way forward is to combine all in a monorepo - inspirehep. We have to refactor many things, including gh-actions, compose and Makefile. We need to make sure that we can reuse service and not running 3 different postgres services for example.

**Comment by DonHaul** [comment]
Regarding the merging of dockercompose.

The dockercomposefiles we currently have will not be deleted for now. i.e.:
- There will be a `backoffice-repo/dockercompose.yaml` for BO
- There will be still a `docker-compose.yml` and `docker-compose.services.yml` for HEP

new developments will be done in `docker-compose-full.yml`

We have the following services for each 'repo', some of which are redundants and some of which the ports are clashing:

service | HEP | BO
-- | -- | --
ES | 9200 / 9300 / 9600 | 9200
cache/redis | 6379 | no port
flower | 5555 | requires command run
hep record editor | 8081 |  
hep ui | 3000 |  
rabbit mq | 15672 / 5672 | no port
web | 7777 / 8000 | 8000
localstack | 4566 / 4572 |  
Postgres | 5432 | 5432
Postgres Airflow |   | no port
airflow webserver |   | 8080
ui | 8080 |  
airflow worker |   | no port
airflow triggerer |   | no port
airflow scheduler |   | no port
hep worker | no port |  


Next actions:
- [ ] Merge the 2 opensearches
- [ ] Merge the 2/3 postgreses
- [ ] Merge the flowers
- [ ] Merge the opensearches
- [ ] Unclash web-hep and web-bo ports (8000)
- [ ] Unclash airflow-webserver and ui ports (8080)
