### ISSUE TITLE
don't trust the frontend to decide whether a user can make a claim

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#72]
From https://cern-rcs-sis.zulipchat.com/#narrow/stream/310485-inspire/topic/claiming/near/287180663:

> Something I was wondering: do I understand correctly that we don't check in the `/assign/author` view https://github.com/inspirehep/inspirehep/blob/ff01a96f7100f7693bbed02f52047020979f31a2/backend/inspirehep/assign/views.py#L98 that the user is actually allowed to perform the claims he's doing? in other words, the frontend does the checks and decides which bucket in https://github.com/inspirehep/inspirehep/blob/ff01a96f7100f7693bbed02f52047020979f31a2/backend/inspirehep/assign/views.py#L92-L94 to put the recid in. If that's indeed the case, it doesn't seem super safe, as nothing prevents a user to perform random claims, bypassing all checks, by calling the API directly.

It would be safer if the frontend didn't do any permission checks to decide which case we're in (still needed to display the buttons in the correct state on the UI), but passed all record IDs to the backend, which would do the checks to decide whether to allow claiming or create an RT ticket then return all the needed data (including counts) back to the frontend in the response.

**Comment by MJedr** [comment]
**TECH NOTES**
**backend**
The problem is that in order to know which function to call and what message to return to the frontend we'll have to query records in a view, which might be not a good option with a big number of records to be claimed. If we do it inside of a task we won't be able to know if the [ticket was created](https://github.com/inspirehep/inspirehep/blob/2980d09ea36b03613323eb668eca9baadc83b8d9/backend/inspirehep/assign/views.py#L135) and what message to display in the frontend. 
* in [author assign view](https://github.com/inspirehep/inspirehep/blob/2980d09ea36b03613323eb668eca9baadc83b8d9/backend/inspirehep/assign/views.py#L98) in the beginning add a check for papers that are already claimed (check for `curated_relation` in a from_author) and papers with not matching name (use `can_claim` function for that, it should be refactored) and put them in a corresponding list. Also check before if [the author is stub](https://github.com/inspirehep/inspirehep/blob/2980d09ea36b03613323eb668eca9baadc83b8d9/backend/inspirehep/assign/views.py#L124-L126) and in that case don't add anything to `claimed_literature_recids`. Don't do this check if request is coming from curator or `to_author_recid` is None (that means that it's own profile claiming and for that case we don't do the checks)

**ui**
* [here](https://github.com/inspirehep/inspirehep/blob/2980d09ea36b03613323eb668eca9baadc83b8d9/ui/src/actions/authors.js#L184-L185) pass `literature_recids` taken from state instead (`publicationSelection`).

**Comment by MJedr** [comment]
**TECH NOTES**
1. In assign views create new views:
    * one for assigning for curators and own profile claiming (arguments: `literature_ids`, `from_author`, `to_author`)
    * one for unassigning for curators and own profile claiming (arguments: `literature_ids`, `from_author`, `to_author` or stub)
    * one for assigning from different profile (arguments: `from_author`, `to_author`, `already_claimed_literature_ids`, `not_compatibile_name_literature_ids`)
 
In each endpoint check required permissions for action (role: curator, `can_claim` for own profile, different profile: if user has an orcid).
For different profile claiming pull all the records that are in the incoming ids lists and verify if they are correctly classified. Also, reclassify them by looking if the author is stub (as we do currently).
Adjust frontend actions.
