### ISSUE TITLE
support `\include` in plotextractor

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#83]
From https://rt.inspirehep.net/Ticket/Display.html?id=1256578

Plotextractor can extract figures not only from the main LaTeX file, but also from other files included in the main one with `\input{secondary_file}`. The problem is that it doesn't support `\include` but only `\input` to include secondary files. This should be extended, replicating the logic of https://github.com/inspirehep/plotextractor/blob/ebc6c0790d52f906479f9f7806580fe2f5af30a2/plotextractor/extractor.py#L359-L379. Note that some care might need to be taken to avoid confusion with `\includegraphics` which contains `\include` as a substring.

Also note that there are two branches, a `master` branch on Python 3 (currently not is use) and a `maintenance` branch on Python 2 (used by `next`).

Test case: https://inspirehep.net/literature/2106233 should have all its figures extracted.

**Comment by drjova** [comment]
@michamos could you please add more details?

**Comment by michamos** [comment]
@drjova done, let me know if you need more info

**Comment by drjova** [comment]
Thanks

**Comment by MJedr** [comment]
**TECH NOTES**
1. Add `\include` [here](https://github.com/inspirehep/plotextractor/blob/ebc6c0790d52f906479f9f7806580fe2f5af30a2/plotextractor/extractor.py#L191) as a regex (so that we can do an exact match later)
2. Replicate logic from [here](https://github.com/inspirehep/plotextractor/blob/ebc6c0790d52f906479f9f7806580fe2f5af30a2/plotextractor/extractor.py#L359-L379) but to find an interesting header (`\include`) use a regex (to not confuse it with `\includegraphics`)
