### ISSUE TITLE
Tests with firefox 102 fail

### ISSUE THREAD

**Issue by nooraangelva** [cern-sis/issues-inspire#85]
Failures are from submissions and they are about the dropdowns.
Tests didn't fail with version 101.

There is an issue about this on [cypress](https://github.com/cypress-io/cypress/issues/22760)

**Comment by karolina-siemieniuk-morawska** [comment]
The original issue of Firefox tests failing caused by Cypress not being able to click on some buttons, due to dropdowns not collapsing, has been fixed according to instruction provided in the issue linked above. Unfortunately, after turning the test back on in the github workflow file, Cypress now has trouble connecting to FF browser during test. The issue appears to be common, as it was reported many times to Cypress in the past weeks, yet no solution was found for this. 

https://github.com/cypress-io/cypress/issues/22086
https://github.com/cypress-io/cypress/issues/23215
